/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        bg: {
          primary: '#04040f',
          secondary: '#080818',
          card: '#0d1b2e',
          'card-alt': '#0a1628',
        },
        accent: {
          cyan:   '#00e5ff',
          blue:   '#0066ff',
          purple: '#7c4dff',
          green:  '#00e676',
          yellow: '#ffd600',
          pink:   '#ff4081',
        },
        border: { DEFAULT: '#1e3a5f' },
        brand: {
          50:  '#e0fffe',
          100: '#b3fffe',
          200: '#80fffd',
          300: '#4dfffc',
          400: '#26fffa',
          500: '#00e5ff',
          600: '#00b8d4',
          700: '#0088a3',
          800: '#005f75',
          900: '#003847',
        },
      },
      fontFamily: {
        heading: ['Space Grotesk', 'sans-serif'],
        sans:    ['Inter', 'sans-serif'],
        mono:    ['JetBrains Mono', 'monospace'],
      },
      animation: {
        'glow-pulse':   'glowPulse 2s ease-in-out infinite',
        'glow-cyan':    'glowCyan 2s ease-in-out infinite',
        'float':        'float 3s ease-in-out infinite',
        'float-slow':   'float 5s ease-in-out infinite',
        'shimmer':      'shimmer 2s linear infinite',
        'spin-slow':    'spin 8s linear infinite',
        'marquee':      'marquee 30s linear infinite',
        'gradient-x':   'gradientX 4s ease infinite',
        'bounce-slow':  'bounce 2s infinite',
        'ping-slow':    'ping 2.5s cubic-bezier(0,0,0.2,1) infinite',
        'draw-line':    'drawLine 1.5s ease forwards',
        'count-up':     'countUp 0.5s ease-out forwards',
      },
      keyframes: {
        glowPulse: {
          '0%,100%': { boxShadow: '0 0 10px #00e5ff, 0 0 20px #00e5ff40' },
          '50%':     { boxShadow: '0 0 25px #00e5ff, 0 0 50px #00e5ff60, 0 0 80px #00e5ff20' },
        },
        glowCyan: {
          '0%,100%': { textShadow: '0 0 10px #00e5ff80' },
          '50%':     { textShadow: '0 0 20px #00e5ff, 0 0 40px #00e5ff80' },
        },
        float: {
          '0%,100%': { transform: 'translateY(0px)' },
          '50%':     { transform: 'translateY(-12px)' },
        },
        shimmer: {
          '0%':   { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition:  '200% 0' },
        },
        marquee: {
          '0%':   { transform: 'translateX(0)' },
          '100%': { transform: 'translateX(-50%)' },
        },
        gradientX: {
          '0%,100%': { backgroundPosition: '0% 50%' },
          '50%':     { backgroundPosition: '100% 50%' },
        },
        drawLine: {
          '0%':   { width: '0%' },
          '100%': { width: '100%' },
        },
        slideUp: {
          '0%':   { opacity: '0', transform: 'translateY(30px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        slideDown: {
          '0%':   { opacity: '0', transform: 'translateY(-30px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        slideLeft: {
          '0%':   { opacity: '0', transform: 'translateX(30px)' },
          '100%': { opacity: '1', transform: 'translateX(0)' },
        },
        slideRight: {
          '0%':   { opacity: '0', transform: 'translateX(-30px)' },
          '100%': { opacity: '1', transform: 'translateX(0)' },
        },
        scaleIn: {
          '0%':   { opacity: '0', transform: 'scale(0.95)' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        },
        fadeIn: {
          '0%':   { opacity: '0' },
          '100%': { opacity: '1' },
        },
        blob: {
          '0%, 100%': { transform: 'translate(0, 0) scale(1)' },
          '25%':      { transform: 'translate(20px, -30px) scale(1.1)' },
          '50%':      { transform: 'translate(-20px, 20px) scale(0.9)' },
          '75%':      { transform: 'translate(30px, 20px) scale(1.05)' },
        },
        pulse3d: {
          '0%, 100%': { transform: 'scale(1)', opacity: '1' },
          '50%':      { transform: 'scale(1.05)', opacity: '0.8' },
        },
        wiggle: {
          '0%, 100%': { transform: 'rotate(-3deg)' },
          '50%':      { transform: 'rotate(3deg)' },
        },
        heartbeat: {
          '0%, 100%': { transform: 'scale(1)' },
          '14%':      { transform: 'scale(1.15)' },
          '28%':      { transform: 'scale(1)' },
          '42%':      { transform: 'scale(1.15)' },
          '70%':      { transform: 'scale(1)' },
        },
        meteor: {
          '0%':   { transform: 'rotate(215deg) translateX(0)', opacity: '1' },
          '70%':  { opacity: '1' },
          '100%': { transform: 'rotate(215deg) translateX(-500px)', opacity: '0' },
        },
      },
      animation: {
        'glow-pulse':   'glowPulse 2s ease-in-out infinite',
        'glow-cyan':    'glowCyan 2s ease-in-out infinite',
        'float':        'float 3s ease-in-out infinite',
        'float-slow':   'float 5s ease-in-out infinite',
        'shimmer':      'shimmer 2s linear infinite',
        'spin-slow':    'spin 8s linear infinite',
        'marquee':      'marquee 30s linear infinite',
        'marquee-fast': 'marquee 15s linear infinite',
        'gradient-x':   'gradientX 4s ease infinite',
        'bounce-slow':  'bounce 2s infinite',
        'ping-slow':    'ping 2.5s cubic-bezier(0,0,0.2,1) infinite',
        'draw-line':    'drawLine 1.5s ease forwards',
        'count-up':     'countUp 0.5s ease-out forwards',
        'slide-up':     'slideUp 0.6s ease-out forwards',
        'slide-down':   'slideDown 0.6s ease-out forwards',
        'slide-left':   'slideLeft 0.6s ease-out forwards',
        'slide-right':  'slideRight 0.6s ease-out forwards',
        'scale-in':     'scaleIn 0.5s ease-out forwards',
        'fade-in':      'fadeIn 0.5s ease-out forwards',
        'blob':         'blob 8s ease-in-out infinite',
        'pulse-3d':     'pulse3d 2s ease-in-out infinite',
        'wiggle':       'wiggle 1s ease-in-out infinite',
        'heartbeat':    'heartbeat 1.5s ease-in-out infinite',
        'meteor':       'meteor 5s linear infinite',
      },
      backgroundSize: { '200': '200% auto', '300': '300% 300%' },
      backdropBlur: { xs: '2px' },
      transitionTimingFunction: {
        'bounce-in': 'cubic-bezier(0.68, -0.55, 0.265, 1.55)',
        'smooth': 'cubic-bezier(0.4, 0, 0.2, 1)',
      },
    },
  },
  plugins: [],
}
